git rm ./commercial/GA1/3rd-party-license-agreements.md
git rm ./commercial/GA1/commercial.-vsa-overview.md
git rm ./commercial/GA1/commercial.backup-restore-GA.md
git rm ./commercial/GA1/commercial.dashboard.how-works.md
git rm ./commercial/GA1/commercial.dashboard.launch.md
git rm ./commercial/GA1/commercial.eula.md
git rm ./commercial/GA1/commercial.faq.md
git rm ./commercial/GA1/commercial.glossary.md
git rm ./commercial/GA1/commercial.index.md
git rm ./commercial/GA1/commercial.install-3par.md
git rm ./commercial/GA1/commercial.install-add-nodes.md
git rm ./commercial/GA1/commercial.install-GA-CSV.md
git rm ./commercial/GA1/commercial.install-GA-DNSaaS.md
git rm ./commercial/GA1/commercial.install-GA-ESX-Proxy.md
git rm ./commercial/GA1/commercial.install-GA-esx.md
git rm ./commercial/GA1/commercial.install-GA-JSON.md
git rm ./commercial/GA1/commercial.install-GA-kvm.md
git rm ./commercial/GA1/commercial.install-GA-LDAP.md
git rm ./commercial/GA1/commercial.install-GA-NTP.md
git rm ./commercial/GA1/commercial.install-GA-overview.md
git rm ./commercial/GA1/commercial.install-GA-ovsvapp.md
git rm ./commercial/GA1/commercial.install-GA-prereqs.md
git rm ./commercial/GA1/commercial.install-GA-security.md
git rm ./commercial/GA1/commercial.install-GA-supportmatrix.md
git rm ./commercial/GA1/commercial.install-GA-verify.md
git rm ./commercial/GA1/commercial.install-GA-vsa.md
git rm ./commercial/GA1/commercial.map.volumetype.md
git rm ./commercial/GA1/commercial.name-resolution.md
git rm ./commercial/GA1/commercial.networking-maskedIP.md
git rm ./commercial/GA1/commercial.related-topics.md
git rm ./commercial/GA1/commercial.release-notes.md
git rm ./commercial/GA1/commercial.sirius-cli-workflow.md
git rm ./commercial/GA1/commercial.sirius-cli.md
git rm ./commercial/GA1/commercial.site-index.md
git rm ./commercial/GA1/commercial.technical-overview.ga.md
git rm ./commercial/GA1/commercial.troubleshooting.md
git rm ./commercial/GA1/commercial.undercloud-admin-settings.md
git rm ./commercial/GA1/commercial.undercloud-admin-updates-and-extensions.md
git rm ./commercial/GA1/commercial.undercloud-eon-cli.md
git rm ./commercial/GA1/commercial.undercloud-horizon-overview.md
git rm ./commercial/GA1/commercial.undercloud-oc-config-esx.md
git rm ./commercial/GA1/commercial.undercloud-oc-config-storeserv.md
git rm ./commercial/GA1/commercial.undercloud-oc-config-storevirtual.md
git rm ./commercial/GA1/commercial.undercloud-oc-config.md
git rm ./commercial/GA1/commercial.undercloud-resource-esx-manage-vm.md
git rm ./commercial/GA1/commercial.undercloud-resource-esx.md
git rm ./commercial/GA1/commercial.undercloud-resources-overview.md
git rm ./commercial/GA1/commercial.undercloud-resources-storage.md
git rm ./commercial/GA1/commercial.undercloud-storage-storeserv.md
git rm ./commercial/GA1/commercial.undercloud-storage-storevirtual.md
git rm ./commercial/GA1/commercial.update-101-devplat.md
git rm ./commercial/GA1/commercial.update-101-devplat.stopstart.md
git rm ./commercial/GA1/commercial.update-101-monitor.md
git rm ./commercial/GA1/commercial.update-101-obtaining.md
git rm ./commercial/GA1/commercial.update-101-overcloud.md
git rm ./commercial/GA1/commercial.update-101-overview.md
git rm ./commercial/GA1/commercial.update-101-prereqs.md
git rm ./commercial/GA1/commercial.update-101-seed.md
git rm ./commercial/GA1/commercial.update-101-troubleshooting.md
git rm ./commercial/GA1/commercial.update-101-undercloud.md
git rm ./commercial/GA1/commercial.vlan-providernetwork.md
git rm ./commercial/GA1/commerical.flexible-control-pane-installation.md
git rm ./commercial/GA1/commerical.flexible-control-pane-overview.md
git rm ./commercial/GA1/commerical.high-availability.md
git rm ./commercial/GA1/commerical.services-compute-overview.md
git rm ./commercial/GA1/commerical.services-dns-overview.md
git rm ./commercial/GA1/commerical.services-dvr-overview.md
git rm ./commercial/GA1/commerical.services-eon-overview.md
git rm ./commercial/GA1/commerical.services-eve-overview.md
git rm ./commercial/GA1/commerical.services-focus-overview.md
git rm ./commercial/GA1/commerical.services-horizon-overview.md
git rm ./commercial/GA1/commerical.services-identity-overview.md
git rm ./commercial/GA1/commerical.services-imaging-overview.md
git rm ./commercial/GA1/commerical.services-ironic-overview.md
git rm ./commercial/GA1/commerical.services-networking-overview.md
git rm ./commercial/GA1/commerical.services-object-overview.md
git rm ./commercial/GA1/commerical.services-object-pyringos.md
git rm ./commercial/GA1/commerical.services-orchestration-overview.md
git rm ./commercial/GA1/commerical.services-overview.md
git rm ./commercial/GA1/commerical.services-remove-replace-failed-overcloud-nodes.md
git rm ./commercial/GA1/commerical.services-reporting-overview.md
git rm ./commercial/GA1/commerical.services-scale-out-swift.md
git rm ./commercial/GA1/commerical.services-sherpa-accessing-ui.md
git rm ./commercial/GA1/commerical.services-sherpa-overview.md
git rm ./commercial/GA1/commerical.services-sirius-overview.md
git rm ./commercial/GA1/commerical.services-swift-deployment-add-disk-account-container.md
git rm ./commercial/GA1/commerical.services-swift-deployment-add-disk-scale-out-object-ring.md
git rm ./commercial/GA1/commerical.services-swift-deployment-add-disk-starter-object-ring.md
git rm ./commercial/GA1/commerical.services-swift-deployment-add-disk-storage-node.md
git rm ./commercial/GA1/commerical.services-swift-deployment-add-proxy-node.md
git rm ./commercial/GA1/commerical.services-swift-deployment-expand-swift-cluster.md
git rm ./commercial/GA1/commerical.services-swift-deployment-monitor-health-check.md
git rm ./commercial/GA1/commerical.services-swift-deployment-monitor-replica-swift-status.md
git rm ./commercial/GA1/commerical.services-swift-deployment-monitor-swift-cluster.md
git rm ./commercial/GA1/commerical.services-swift-deployment-monitor-swift-disk.md
git rm ./commercial/GA1/commerical.services-swift-deployment-part-power.md
git rm ./commercial/GA1/commerical.services-swift-deployment-provision-swift-node.md
git rm ./commercial/GA1/commerical.services-swift-deployment-shrink-remove-exisitng-disk.md
git rm ./commercial/GA1/commerical.services-swift-deployment-shrink-remove-proxy-node.md
git rm ./commercial/GA1/commerical.services-swift-deployment-shrink-remove-scale-out-object-storage-node.md
git rm ./commercial/GA1/commerical.services-swift-deployment-shrink-swift-cluster.md
git rm ./commercial/GA1/commerical.services-swift-deployment.md
git rm ./commercial/GA1/commerical.services-swift-diagnosis-disk-health-hpssacli.md
git rm ./commercial/GA1/commerical.services-tripleo-overview.md
git rm ./commercial/GA1/commerical.services-volume-overview.md
git rm ./devplatform/devplatform.ALS-developer-trial-quick-start.md
git rm ./devplatform/devplatform.appdev.md
git rm ./devplatform/devplatform.database-ALS.md
git rm ./devplatform/devplatform.database-instance.md
git rm ./devplatform/devplatform.deploy-ALS.md
git rm ./devplatform/devplatform.eclipse.md
git rm ./devplatform/devplatform.eula.md
git rm ./devplatform/devplatform.index.md
git rm ./devplatform/devplatform.marketplace.install.md
git rm ./devplatform/devplatform.related-topics.md
git rm ./devplatform/devplatform.release-notes.md
git rm ./devplatform/devplatform.sysadmin.md
git rm ./devplatform/devplatform.thirdparty.licensing.md
git rm ./devplatform/devplatform.using-messaging-service-with-ALS.md
git rm ./devplatform/devplatform.using-the-messaging-service.md
git rm ./devplatform/devplatform_commercial_install.md
git rm ./devplatform/devplatform_community_install.md
git rm ./devplatform/helion/index.html.md
git rm ./devplatform/helion/admin/index.html.md
git rm ./devplatform/helion/admin/best-practices/index.html.md
git rm ./devplatform/helion/admin/best-practices/logging-examples.html.md
git rm ./devplatform/helion/admin/cluster/autoscaling.html.md
git rm ./devplatform/helion/admin/cluster/cloud-init.html.md
git rm ./devplatform/helion/admin/cluster/external-db.html.md
git rm ./devplatform/helion/admin/cluster/harbor.html.md
git rm ./devplatform/helion/admin/cluster/index.html.md
git rm ./devplatform/helion/admin/console/app-store.html.md
git rm ./devplatform/helion/admin/console/customize.html.md
git rm ./devplatform/helion/admin/console/index.html.md
git rm ./devplatform/helion/admin/reference/add-service.html.md
git rm ./devplatform/helion/admin/reference/architecture.html.md
git rm ./devplatform/helion/admin/reference/groups.html.md
git rm ./devplatform/helion/admin/reference/kato-ref.html.md
git rm ./devplatform/helion/admin/reference/known-issues.html.md
git rm ./devplatform/helion/admin/reference/troubleshoot.html.md
git rm ./devplatform/helion/admin/server/aok.html.md
git rm ./devplatform/helion/admin/server/configuration.html.md
git rm ./devplatform/helion/admin/server/docker.html.md
git rm ./devplatform/helion/admin/server/index.html.md
git rm ./devplatform/helion/admin/server/logging.html.md
git rm ./devplatform/helion/admin/server/operations.html.md
git rm ./devplatform/helion/admin/server/router.html.md
git rm ./devplatform/helion/admin/server/upgrade.html.md
git rm ./devplatform/helion/CLI/ALS_Client_Downloads.md
git rm ./devplatform/helion/user/index.html.md
git rm ./devplatform/helion/user/client/index.html.md
git rm ./devplatform/helion/user/console/index.html.md
git rm ./devplatform/helion/user/deploy/app-debug.html.md
git rm ./devplatform/helion/user/deploy/app-logs.html.md
git rm ./devplatform/helion/user/deploy/buildpack.html.md
git rm ./devplatform/helion/user/deploy/index.html.md
git rm ./devplatform/helion/user/deploy/manifestyml.html.md
git rm ./devplatform/helion/user/deploy/newrelic.html.md
git rm ./devplatform/helion/user/deploy/orgs-spaces.html.md
git rm ./devplatform/helion/user/deploy/other-frameworks.html.md
git rm ./devplatform/helion/user/deploy/stackatoyml.html.md
git rm ./devplatform/helion/user/deploy/languages/clojure.html.md
git rm ./devplatform/helion/user/deploy/languages/go.html.md
git rm ./devplatform/helion/user/deploy/languages/java.html.md
git rm ./devplatform/helion/user/deploy/languages/node.html.md
git rm ./devplatform/helion/user/deploy/languages/php.html.md
git rm ./devplatform/helion/user/deploy/languages/ruby.html.md
git rm ./devplatform/helion/user/quick-start/index.html.md
git rm ./devplatform/helion/user/reference/client-ref.html.md
git rm ./devplatform/helion/user/reference/environment.html.md
git rm ./devplatform/helion/user/reference/glossary.html.md
git rm ./devplatform/helion/user/reference/troubleshoot.html.md
git rm ./devplatform/helion/user/services/data-services.html.md
git rm ./devplatform/helion/user/services/filesystem.html.md
git rm ./devplatform/helion/user/services/memcached.html.md
git rm ./devplatform/helion/user/services/port-service.html.md
git rm ./devplatform/helion/user/services/user-provided.html.md
git rm ./devplatform/workbook/database/database.java.md
git rm ./devplatform/workbook/database/database.node.md
git rm ./devplatform/workbook/database/database.php.md
git rm ./devplatform/workbook/helloWorld/helloworld.java.md
git rm ./devplatform/workbook/helloWorld/helloworld.node.md
git rm ./devplatform/workbook/helloWorld/helloworld.php.md
git rm ./devplatform/workbook/messaging/messaging.java.md
git rm ./devplatform/workbook/messaging/messaging.node.md
git rm ./devplatform/workbook/messaging/messaging.php.md

